# Generated by Django 4.2.14 on 2024-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
